name: CI/CD - Deploy FinTrack

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Create inventory
        run: |
          echo "[web]" > inventory.ini
          echo "${{ secrets.DEPLOY_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/site.yml -i inventory.ini \
            --extra-vars "repo_version=main"
      - name: Force restart gunicorn
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEPLOY_HOST }} \
          "sudo systemctl restart fintrack-gunicorn"

